import 'package:flutter/material.dart';

class Munshiganj extends StatefulWidget {
  const Munshiganj({Key? key}) : super(key: key);

  @override
  _MunshiganjState createState() => _MunshiganjState();
}

class _MunshiganjState extends State<Munshiganj> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(
            child: Text("Munshiganj")
        ),
      ),
      body: Column (
        children: [
          Image.network("https://images.prothomalo.com/prothomalo-english%2Fimport%2Fmedia%2F2017%2F02%2F21%2F362f53fa725c41de3fc8cc1b5c48bcd6-munsigonj.jpg?auto=format&fit=fill&bg=000000&q=35&w=1200",
            height: 200,
            width: 500,
          ),

          Text("Munshiganj (Bengali: মুন্সিগঞ্জ), also historically known as Bikrampur, is a district[2] in central Bangladesh. It is a part of the Dhaka Division and borders Dhaka District.[3]"
              "Total land area is 235974 acres (954 km2), out of which 138472 acres (560 km2) are cultivable and 5609 acres (23 km2) are fallow land. It has no forest area. 40277 acres (163 km2) of land is irrigated while 26242 acres (106 km2) of land is under river. It has 14 rivers of 155 km passing through.[4]"
              "The district consists of 6 upazilas:[3]"

              "Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila""Lohajang Upazila"
              "Sreenagar Upazila"
              "Munshiganj Sadar Upazila"
              "Sirajdikhan Upazila"
              "Tongibari Upazila"
              "Gazaria Upazila"


          "M. Hamidullah Khan, Bangladesh Forces, Sector Commander, Sector 11, Bangladesh War of Independence 1971[6]"
              "Jagadish Chandra Bose, Great Bengali physicist[7]Badal Gupta, revolutionary against British IndiaBenoy Basu, revolutionary against British IndiaDinesh Gupta, revolutionary against British IndiaSarojini Naidu, PoliticianChittaranjan Das"
              ""
              "")
        ],
      ),
    );
  }
}
